### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by agirorn** [AndreasMadsen/trace#22]
When i try to use this in node v0.10.32 which is old I know. I get this error. Is there no way to use this or something to get a proper trace in node 0.10 ?

```shell
const chain = require('stack-chain');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/agirorn/hal.js/backend/spec/helpers/trace.helper.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

```

**Comment by AndreasMadsen** [comment]
Unfortunately it's not possible to support node 0.10, because it doesn't have the necessary features, specifically async_wrap. See #20 for more details.

An important difference between node 0.12 (discussed in #20) and node 0.10, is that node 0.12 has some async_wrap support, while node 0.10 has none.
